### ISSUE TITLE
crabConfigParser: Move from 'tools3a' to 'libs3a'

### ISSUE THREAD

**Issue by DebbieDuchardt** [Aachen-3A/tools3a#9]
The crabConfigParser is a library not a standalone tool.

**Comment by tobias-pook** [comment]
Yes, you are right, but the idea was to make it easier for collaborators outside of 3A to  use music_crab3 by cloning just one repo.
Maybe some other contributors may chip in with their opinion...

**Comment by olschewski** [comment]
Your argument applies to all libs, as it may happen that someone from outside wants to use a certain tool. It already applies to cesubmit/television for example. If this is a problem, we should merge the libs and tools repos rather than to soften our policy. Apart from that the tools directory is not included in the PYTHONPATH, making the library there harder do include.

**Comment by tobias-pook** [comment]
The issue has been solved in the referenced commits.
Closing the issue.
